#%RAML 1.0 DataType
properties:
  MsgRsHdr:
    type : object
    required: true
    properties:
        RqUID:
          type : string
          description: Request Identifier. Sent by a server as a universally unique identifier for the message. Used to correlate responses with requests. Sent by a client to request the asynchronous response on the previously submitted message.
          required: true
          example: "{0C42D547-D5E8-4DEB-9D69-94BAC81D390F}"
        Status:
          type : object
          required: true
          properties:
            StatusCode:
              type : number
              description: 0 - “OK”; -1 - “BUR. ERROR” (Bureau Error); -2 - “INTERNAL ERROR”; -3 - “LINE ERROR”; -4 - “NO HIT”; -5 - “AUTHENTICATION ERROR”; -6 - “IN_PROC”
              required: true
              example: 0 
            ServerStatusCode:
              type : string
              required: false
              example: "0" 
            Severity:
              type : string
              description: Error; Warn; Info
              required: true
              example: "Info"
            StatusDesc:
              type: string
              description: Explanatory text associated with the status code.
              required: true
              example: "OK"
            AdditionalStatus:
              type: array
              required: false
              items:
                properties:                  
                  StatusCode:
                    type : number
                    required: false
                    example: 0
                  ServerStatusCode:
                    type : string
                    required: false
                    example: "0" 
                  Severity:
                    type : string
                    required: false
                    example: "Info"
                  StatusDesc:
                    type: string
                    required: false
                    example: "OK"
        
  VerificationFlags:
    type: object
    required: false
    properties:
        VerificationFlag:
          type : string
          description: Y; N
          required: true
          example: "Y"
        VCode:
          type : number
          description: Verification Code
          required: true
          example: 0
        VCodeDescription:  
          type : string
          description: Verification Code Description
          required: true
          example: "SSN Matched to Submitted Address"
        