#%RAML 1.0 NamedExample
{
  "providerViews": [
    {
      "provider": "EFX",
      "score": 0,
      "scoreRanges": [
        {
          "low": 0,
          "high": 0,
          "name": "string"
        }
      ],
      "loanRiskRanges": [
        {
          "low": 0,
          "high": 0,
          "name": "string"
        }
      ],
      "scoreReasons": [
        {
          "code": "string",
          "description": "string",
          "creditScoreFactorEffect": "HELPING"
        }
      ]
    }
  ],
  "id": "string",
  "scoreType": "US_EFX",
  "scoreModel": "VANTAGE",
  "generatedDate": "2019-08-24T14:15:22Z"
}