#%RAML 1.0 NamedExample


{
  "MsgRsHdr": {
    "RqUID": "{BCB7DEA5-B79D-4A7B-B369-19C5201F8864}",
    "Status": {
      "StatusCode": 0,
      "Severity": "Info",
      "StatusDesc": "OK"
    }
  },
  "VerificationFlags": {
    "VerificationFlag": "N",
    "VCode": 9,
    "VCodeDescription": "Unable to Match SSN to Address"
  }
}