#%RAML 1.0 NamedExample


{
  "MsgRsHdr": {
    "RqUID": "{0C42D547-D5E8-4DEB-9D69-94BAC81D390F}",
    "Status": {
      "StatusCode": 0,
      "Severity": "Info",
      "StatusDesc": "OK"
    }
  },
  "VerificationFlags": {
    "VerificationFlag": "Y",
    "VCode": 0,
    "VCodeDescription": "SSN Matched to Submitted Address"
  }
}