#%RAML 1.0 NamedExample


{
  "MsgRsHdr": {
    "RqUID": "{450504A7-1C97-436F-95ED-F9E4CCCF9949}",
    "Status": {
      "StatusCode": -2,
      "Severity": "Error",
      "StatusDesc": "SSN must be 9 characters in length"
    }
  }
}