#%RAML 1.0 NamedExample


{
  "MsgRsHdr": {
    "RqUID": "{430EB64B-D078-463A-97E7-DC1491D0ADF7}",
    "Status": {
      "StatusCode": 0,
      "Severity": "Info",
      "StatusDesc": "OK"
    }
  },
  "VerificationFlags": {
    "VerificationFlag": "Y",
    "VCode": 0,
    "VCodeDescription": "SSN Matched to Submitted Name"
  }
}