#%RAML 1.0 NamedExample


{
  "MsgRsHdr": {
    "RqUID": "{7A2D5EA6-4358-41A1-A2BA-45CD891EFB0A}",
    "Status": {
      "StatusCode": -2,
      "Severity": "Error",
      "StatusDesc": "SSN must be 9 characters in length"
    }
  }
}