#%RAML 1.0 NamedExample

  {
  "MsgRsHdr": {
    "RqUID": "{19506275-6B80-4BA8-ACCA-AA534FF90C9C}",
    "Status": {
      "StatusCode": 0,
      "Severity": "Info",
      "StatusDesc": "OK"
    }
  },
  "AreaNum": 111,
  "GroupNum": 22,
  "IssueDateRange": {
    "StartDt": "1934-01-01T00:00:00",
    "EndDt": "1951-12-31T00:00:00"
  },
  "BeginRange": 1,
  "StateProv": "NY",
  "CodeDigit": {
    "Code": "2",
    "Description": "Issued, Beginning and Ending Date Provided"
  },
  "SSNStatus": "Item1"
}