#%RAML 1.0 NamedExample

  {
  "MsgRsHdr": {
    "RqUID": "{39D0DE79-99E3-4B08-A90A-E41ED40BB831}",
    "Status": {
      "StatusCode": -2,
      "Severity": "Error",
      "StatusDesc": "SSN must be 9 characters in length"
    }
  }
}
